---
version: 2.1

orbs:
  docker: agilepathway/docker@0.6.0

executors:
  go:
    docker:
      - image: cimg/go:1.23

workflows:
  build-and-publish-docker-image:
    jobs:
      - go-test
      - compile-mage-scripts
      - docker/publish:
          requires:
            - compile-mage-scripts
          after_checkout:
            - attach_workspace:
                at: .
            - run: sudo cp -r go-scripts/bin/* /usr/local/bin/
          after_build:
            - run:
                name: Evaluate and export docker after build tags
                command: |
                  echo "export AFTER_BUILD_TAGS=$(docker-tags -v)" >> $BASH_ENV
          tag_after_build: |
            $AFTER_BUILD_TAGS,circleci-pipeline-<< pipeline.number >>
      - release:
          # Only run on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/


jobs:

  go-test:
    working_directory: ~/agile-pathway-co-uk
    executor: go
    steps:
      - checkout
      - run:
          name: Run Go tests
          environment:
            INTEGRATION_TEST: "true"
          command: ./scripts/run-go-tests.sh
      - store_test_results:
          path: /tmp/test-reports/go/junit/
      - store_artifacts:
          path: /tmp/test-reports/go/html/
          destination: test-reports

  compile-mage-scripts:
    working_directory: ~/agile-pathway-co-uk
    executor: go
    steps:
      - checkout
      - run:
          name: Install Mage
          command: ./scripts/install-mage.sh
      - run:
          name: Install docker-tags executable
          command: |
            mage -compile go-scripts/bin/docker-tags -goos linux -goarch amd64
      - persist_to_workspace:
          root: .
          paths:
            - go-scripts/bin/*

  release:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
